services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-}
        NEXT_PUBLIC_USAR_MOCK: ${NEXT_PUBLIC_USAR_MOCK:-}
    container_name: nextjs_frontend
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - app-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel
    restart: unless-stopped
    command:
      - "http"
      - "--url=https://${NGROK_DOMAIN_FRONT}"
      - "frontend:3000" # Apunta al servicio 'frontend' en su puerto interno 3000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "127.0.0.1:4040:4040"
    networks:
      - app-network
    depends_on:
      - frontend

networks:
  app-network:
    driver: bridge